[GLOBAL]
pants_version = "2.19.0"

backend_packages = [
    "pants.backend.experimental.javascript",
    "pants.backend.experimental.javascript.lint.prettier",
]

[anonymous-telemetry]
enabled = false
