[GLOBAL]
pants_version = "2.16.0a1"

backend_packages = [
    "pants.backend.experimental.javascript",
    "pants.backend.experimental.javascript.lint.prettier",
]

[anonymous-telemetry]
enabled = false
