on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/main.yaml"
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  NODE_VERSION: 24.x

jobs:
  build:
    runs-on: ubuntu-latest
    # Sometimes actions go out of control, and end up taking 6 hours - capping
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # - name: Lint checking
      #   run: pnpm lint

      - name: Run unit tests
        run: pnpm test

      - name: Build
        run: pnpm build
